[project]
name = "ADKAmi"
version = "0.1.0"
description = "Nền tảng Multi-Agent: Người bạn đồng hành AI cho sinh viên Học viện Bưu chính Viễn thông. Hệ thống được thiết kế để tạo ra một môi trường học tập năng động. Các tác nhân AI sẽ cùng nhau tương tác để chủ động hỗ trợ sinh viên trong việc tìm kiếm tài liệu, giải quyết bài tập khó, lên kế hoạch ôn thi, và cung cấp lời khuyên hữu ích, cá nhân hóa theo từng nhu cầu của người dùng."
authors = [
    {name = "Nguyen Hai Lam", email = "nguyenhailam@gmail.com"}, # Replace real email
]
dependencies = [
    "google-adk>=1.10.0", 
    "litellm>=1.75.5.post1", 
    "urllib3>=2.5.0"
]
requires-python = ">= 3.10"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
dev = [
    "python-dotenv>=1.1.1"
]

[tool.pdm]
distribution = false
